name: CI - API Gorest com Relatório

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código-fonte
      - name: Checkout do código
        uses: actions/checkout@v4

      # Instalar Node.js e Newman
      - name: Configurar ambiente
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar Newman
        run: npm install -g newman

      # Criar pasta para armazenar relatórios
      - name: Criar pasta de relatórios
        run: mkdir -p newman-reports

      # Executar testes com Postman e salvar relatório
      - name: Testar API Gorest com massa de dados
        run: newman run "API gorest.postman_collection.json" -e "API_gorest_env.json" --iteration-data "dados_csv.csv" \
          --reporters json, html \
          --reporter-json-export newman-reports/report.json \
          --reporter-html-export newman-reports/report.html

      # Upload dos relatórios como artefatos
      - name: Upload dos relatórios do Newman
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: newman-reports/
